/*
  Lighthouse → Frontier syntax code generator
  Maps ARC plan/code output to .fr source for native mobile compilation.
*/

function escapeFrontierString(value) {
  return String(value || '')
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n');
}

function slugify(value) {
  return String(value || 'app')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_|_$/g, '') || 'app';
}

function generateFrontierStep(step, index) {
  const desc = escapeFrontierString(step.description || step.title || `step_${index + 1}`);
  return `// Step ${step.step || index + 1}: ${desc}`;
}

function generateFrontierUI(code) {
  const files = code?.files || [];
  const lines = [];

  for (const file of files) {
    const name = file.path?.split('/').pop() || 'module';
    lines.push(`// Source: ${name}`);
    if (file.description) {
      lines.push(`// ${escapeFrontierString(file.description)}`);
    }
  }

  lines.push('screen.add_text("Built by Lighthouse — compiled to native machine code.");');
  lines.push('screen.add_button("run_app", "Run", "button_click:run");');
  lines.push('screen.add_text_input("user_input", "Enter a command...");');

  return lines.join('\n      ');
}

function generateFrontierCode(arcResult) {
  const { plan = {}, code = {}, analysis = {}, request = '' } = arcResult;
  const appName = plan.suggestedName || analysis.suggestedName || slugify(request).slice(0, 32) || 'lighthouse_app';
  const title = escapeFrontierString(plan.steps?.[0]?.description || analysis.summary || request || 'My App');

  const steps = (plan.steps || []).map((step, i) => generateFrontierStep(step, i)).join('\n    ');

  return `// Generated by Lighthouse ARC → Frontier native mobile target
module ${slugify(appName)};

import frontier.ui.{Screen, Button, List, TextInput};
import frontier.storage.{Database, Query};
import frontier.ai.{LocalModel, Inference};

${steps}

fn main() -> void {
  let screen = Screen::new("${title}");
  ${generateFrontierUI(code)}
  screen.render();
}
`;
}

function attachFrontierToArcResult(arcResult) {
  if (!arcResult?.code?.files) return arcResult;

  const frontierSource = generateFrontierCode(arcResult);
  const appName = slugify(
    arcResult.plan?.suggestedName ||
    arcResult.analysis?.suggestedName ||
    arcResult.request ||
    'app'
  );

  const frontierFile = {
    path: `src/${appName}/app.fr`,
    description: 'Frontier native mobile source — compiles to ARM binary (no WebView)',
    content: frontierSource,
    language: 'frontier'
  };

  const hasFrontier = arcResult.code.files.some(f => f.path?.endsWith('.fr'));
  if (!hasFrontier) {
    arcResult.code.files.push(frontierFile);
  }

  arcResult.frontier = {
    path: frontierFile.path,
    target: 'native-mobile',
    runtime: 'frontier-mobile-runtime'
  };

  return arcResult;
}

module.exports = {
  generateFrontierCode,
  attachFrontierToArcResult,
  generateFrontierStep,
  generateFrontierUI
};
