plugins {
    id 'com.android.application'
}

android {
    namespace 'org.lighthouse.frontier'
    compileSdk 34

    defaultConfig {
        applicationId 'org.lighthouse.frontier'
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName '1.0.0'
        ndk {
            abiFilters 'arm64-v8a', 'armeabi-v7a', 'x86_64'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }

    packagingOptions {
        jniLibs {
            useLegacyPackaging true
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
}
